const FETCH_CITY_REQUEST = "home/FETCH_CITY_REQUEST";
const FETCH_CITY_SUCCESS = "home/FETCH_CITY_SUCCESS";
const FETCH_CITY_ERROR = "home/FETCH_CITY_ERROR";

export default {
	FETCH_CITY_REQUEST,
	FETCH_CITY_SUCCESS,
	FETCH_CITY_ERROR
};
