const FETCH_CITY_REQUEST = "home/FETCH_CITY_REQUEST";
const FETCH_CITY_SUCCESS = "home/FETCH_CITY_SUCCESS";
const FETCH_CITY_ERROR = "home/FETCH_CITY_ERROR";
const SELECT_CITY = "home/SELECT_CITY";

const FETCH_CURRENT_WEATHER_REQUEST = "home/FETCH_CURRENT_WEATHER_REQUEST";
const FETCH_CURRENT_WEATHER_SUCCESS = "home/FETCH_CURRENT_WEATHER_SUCCESS";
const FETCH_CURRENT_WEATHER_ERROR = "home/FETCH_CURRENT_WEATHER_ERROR";

export default {
	FETCH_CITY_REQUEST,
	FETCH_CITY_SUCCESS,
	FETCH_CITY_ERROR,
	SELECT_CITY,
	FETCH_CURRENT_WEATHER_REQUEST,
	FETCH_CURRENT_WEATHER_SUCCESS,
	FETCH_CURRENT_WEATHER_ERROR
};
